### ISSUE TITLE
Crash submitting a filter (until) with time in milliseconds

### ISSUE THREAD

**Issue by franzos** [barkyq/gnost-relay#11]
```
gnost_relay_service | panic: failed to encode args[2]: unable to encode 1693170183133 into binary format for int4 (OID 23): 1693170183133 is greater than maximum value for int4
gnost_relay_service | 
gnost_relay_service | goroutine 55 [running]:
gnost_relay_service | main.ReqSubmissionHandler.func2(0xc00010a240?, 0xc00009fed0, 0xc00009fe48, 0xc00039e030, {0xc00009fdc8, 0x0, 0x0}, 0xc000394040, 0x0?)
gnost_relay_service |   /go/src/github.com/barkyq/gnost-relay/main.go:615 +0x1af
gnost_relay_service | main.ReqSubmissionHandler(0xc0002a6300, 0xc0002a6360, 0xc00010a240, 0x0?)
gnost_relay_service |   /go/src/github.com/barkyq/gnost-relay/main.go:653 +0x38e
gnost_relay_service | created by main.main in goroutine 1
gnost_relay_service |   /go/src/github.com/barkyq/gnost-relay/main.go:167 +0x846
nginx_service  | 172.18.0.1 - - [27/Aug/2023:21:03:13 +0000] "GET / HTTP/1.1" 101 83 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0" "-"
gnost_relay_service exited with code 2
```

**Comment by barkyq** [comment]
thanks, will fix this soon, a bit busy this week!

**Comment by barkyq** [comment]
Hi Franzos, hope it is fixed for you now

**Comment by franzos** [comment]
@barkyq thank you very much! I'm using `gnost-relay` for local testing and might publish a relay soon. I appreciate your work.
