### ISSUE TITLE
[Fixed] An empty lines resulting crash

### ISSUE THREAD

**Issue by Yonle** [barkyq/gnost-relay#4]
I only do this:
```
~ $ websocat ws://localhost:8080
["AUTH","g0ezuvzAIDAUahnu8qgBGw=="]













^C
~ $ websocat ws://localhost:8080
websocat: WebSocketError: WebSocket protocol error
websocat: error running
~ $
```

In server side:
```
2023/05/25 10:03:43 (gnost-relay) database initialized: 0 expired events deleted
127.0.0.1:16430 false false false
panic: EOF

goroutine 12 [running]:
main.handle_websocket.func3()
        /home/_nostr/gnost-relay/websocket.go:250 +0x10c5
created by main.handle_websocket
        /home/_nostr/gnost-relay/websocket.go:134 +0xa0a
```

**Comment by barkyq** [comment]
Hm will take a look...

**Comment by Yonle** [comment]
Alright. It is no longer panicking.

Suggestion: Maybe send response like `["ERROR", "Reason"]` for invalid data.
