### ISSUE TITLE
Panic when connection reset

### ISSUE THREAD

**Issue by Yonle** [barkyq/gnost-relay#5]
```
panic: read tcp 127.0.0.1:4001->127.0.0.1:26913: read: connection reset by peer

goroutine 84 [running]:
main.handle_websocket.func3()
        /home/_nostr/gnost-relay/websocket.go:198 +0x113f
created by main.handle_websocket
        /home/_nostr/gnost-relay/websocket.go:134 +0xa0a
```

**Comment by barkyq** [comment]
good to close?

**Comment by Yonle** [comment]
Well, it is merged anyways. So closing
